# Generated by Django 4.1 on 2022-08-09 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(default="admin"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(default="admin", upload_to="documents/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
