# Generated by Django 4.1 on 2022-08-13 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_document_description_document_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("img", models.ImageField(blank=True, upload_to="profile_pic/")),
                ("state", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("pin", models.BigIntegerField()),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Gen", "General"),
                            ("OBC", "Other Backwards Caste"),
                            ("SC", "Scheduled Caste"),
                            ("ST", "Scheduled Tribe"),
                        ],
                        max_length=50,
                    ),
                ),
                ("adhaar_number", models.BigIntegerField()),
                ("phone_number", models.CharField(max_length=12)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
