# Generated by Django 4.1 on 2022-08-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="middle_name",),
    ]
