# Generated by Django 4.1 on 2022-08-15 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0005_category_scheme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheme", old_name="endData", new_name="endDate",
        ),
        migrations.AddField(
            model_name="document",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
