# Generated by Django 4.1 on 2022-08-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_enddata_scheme_enddate_document_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="img",
            field=models.ImageField(upload_to="scheme/"),
        ),
    ]
