# Generated by Django 4.1 on 2022-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_profile_highest_qualification_profile_income_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="age_max",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheme",
            name="age_min",
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheme",
            name="created_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="district",
            field=models.CharField(default="Sheikhpura", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheme",
            name="gender",
            field=models.CharField(default="Male", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheme",
            name="income_max",
            field=models.IntegerField(default=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheme",
            name="income_min",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheme",
            name="occupation",
            field=models.CharField(default="Farmer", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheme",
            name="qualification",
            field=models.CharField(default="Matriculation", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheme",
            name="state",
            field=models.CharField(default="Bihar", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scheme", name="category", field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(name="Eligibility",),
    ]
