# Generated by Django 4.1 on 2022-08-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_scheme_age_max_scheme_age_min_scheme_created_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="document", name="description",),
    ]
