# Generated by Django 4.1 on 2022-08-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_document_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="scheme", name="created_date",),
        migrations.AddField(
            model_name="scheme",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.category",
            ),
            preserve_default=False,
        ),
    ]
