# Generated by Django 4.1 on 2022-08-20 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0013_alter_profile_adhaar_number_schemetracking_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="schemeregistration", name="scheme",),
        migrations.RemoveField(model_name="schemeregistration", name="user",),
        migrations.AddField(
            model_name="schemeregistration",
            name="scheme",
            field=models.ManyToManyField(to="app.scheme"),
        ),
        migrations.AddField(
            model_name="schemeregistration",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
