# Generated by Django 4.1 on 2022-08-20 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0014_remove_schemeregistration_scheme_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="schemetracking", name="scheme",),
        migrations.RemoveField(model_name="schemetracking", name="user",),
        migrations.AddField(
            model_name="schemetracking",
            name="scheme",
            field=models.ManyToManyField(to="app.scheme"),
        ),
        migrations.AddField(
            model_name="schemetracking",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
