# Generated by Django 4.1 on 2022-08-20 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0015_remove_schemetracking_scheme_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="schemeregistration", name="scheme",),
        migrations.RemoveField(model_name="schemeregistration", name="user",),
        migrations.RemoveField(model_name="schemetracking", name="scheme",),
        migrations.RemoveField(model_name="schemetracking", name="user",),
        migrations.AddField(
            model_name="schemeregistration",
            name="scheme",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.scheme"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schemeregistration",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schemetracking",
            name="scheme",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.scheme"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schemetracking",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
