# Generated by Django 4.1 on 2022-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_document_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="department",
            field=models.CharField(
                choices=[("IT", "IT"), ("Ag", "Agriculture")], max_length=50
            ),
        ),
        migrations.DeleteModel(name="Category",),
    ]
