# Generated by Django 4.1 on 2022-08-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_scheme_department_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="department",
            field=models.CharField(max_length=50),
        ),
    ]
