# Generated by Django 4.1 on 2022-08-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_profile_email_token_profile_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="documents_required",
            field=models.CharField(default="aadhar", max_length=1000),
            preserve_default=False,
        ),
    ]
