# Generated by Django 4.1 on 2022-08-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_remove_profile_state"),
        ("app", "0021_scheme_documents_required"),
    ]

    operations = []
