# Generated by Django 4.1 on 2022-08-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_merge_20220826_0826"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(default="Bihar", max_length=50),
            preserve_default=False,
        ),
    ]
