# Generated by Django 4.1 on 2022-08-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="user", new_name="auth_user",
        ),
    ]
