# Generated by Django 4.1 on 2022-08-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_user_profile_auth_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="auth_user", new_name="user",
        ),
    ]
